### ISSUE TITLE
Interested in connecting

### ISSUE THREAD

**Issue by nishmeht7** [mykle1/MMM-Spacecraft#1]
Hey @mykle1 I came across your work with MM and it's modules and I love it. I'm working on a very promising smart mirror project that I'd like to talk to you more about. If this sparks your interest, send me an email at nmehta6 at usfca.edu and I'll setup a time for us to talk details! Thanks :)

**Comment by mykle1** [comment]
Thank you for your interest. I do appreciate it. However, I don't have the time I once had and I've lost some interest in this so I wouldn't be able to commit to any sort of collaboration. I wish you every success. Peace!
